- src/App.js
- src/apis/ProductAPICalls.js
- src/components/common/Header.js
- src/components/product/MergeBox.module.css
- src/components/product/MergeMain.module.css
- src/components/product/ProductCategory.js
- src/components/product/ProductCategory.module.css
- src/components/product/ProductCategoryModule.js
- src/components/product/ProductDetailCss.module.css
- src/components/product/ProductItem.module.css
- src/components/product/ProductList.module.css
- src/components/product/ProductMoneyFilter.module.css
- src/components/product/WishList.module.css
- src/pages/product/Merge.js
* * *
꾸러미에서 사용되는 상품 카테고리 선택 박스 작업입니다.
HTML, CSS로 작업했던 거 중에서 일부분을 가져왔습니다.
아직 redux를 값을 처리하는 부분을 구현하지 않았습니다. 참고해주세요.
* * *
트 
값을 받아왔습니다.
작업하는데 문제가 생기거나 공통 컴포넌트가 필요하면 말씀해주세요.
> [FE][FEATURE] 상품 카테고리 출력 작업 중

- src/App.js
- src/apis/ReportAPICalls.js
- src/components/common/AdminHeader.js
- src/modules/ReportModule.js
- src/pages/report/Report.js
- src/pages/report/ReportManagement.js
- src/styles/report/ReportCSS.module.css
- #26 
* * *
* * *
유저 시점에서 신고하기 기능 구현하였습니다.
* * *
```
import { useState } from "react";
import { useDispatch } from "react-redux";
import { callReportRegistAPI } from "../../apis/ReportAPICalls";
import { useNavigate } from "react-router-dom";
import ButtonCSS from '../../styles/Button.module.css'
import ReportCSS from '../../styles/report/ReportCSS.module.css';
function Report() {
const navigate = useNavigate();
// 리덕스를 이용하기 위한 디스 패처 셀렉터 선언
const dispatch = useDispatch();
const [form, setForm] = useState({
reportUserNick: '',
refReportCategoryNo: 0,
productCode: 0,
reportComment: '',
sellStatusCode: 0
});
// form Data Set
const onChangeHandler = (e) => {
setForm({
...form,
[e.target.name]: e.target.value
});
}
console.log("값제대로 나오나요 ?", form);
const onClickExitHandle = () => {
// X 버튼 …
```
>  🤡[FE][FEATURE] 신고기능 insert

- src/apis/ProductAPICalls.js
- src/components/common/PagingBar.js
- src/components/product/MergeBox.js
- src/components/product/MergeCategory.js
- src/components/product/ProductCategory.js
- src/components/product/ProductFilter.js
- src/components/product/ProductItem.js
- src/components/product/ProductList.js
- src/modules/MergeModule.js
- src/modules/PagingModule.js
- src/modules/ProductListModule.js
- src/modules/ProductModule.js
- src/modules/index.js
- src/pages/product/Merge.js
- src/styles/PagingBar.module.css
- src/styles/product/MergeBox.module.css
- src/styles/product/MergeCategory.module.css
- src/styles/product/MergeLayout.module.css
- src/styles/product/ProductList.module.css
* * *
* * *
꾸러미 기능 구현중입니다. - 머지 카테고리 선택하면 URL 바뀌는 걸 구현했습니다.
* * *
추가된 파일 없음
* * *
state 관련해서 reducer 1개에서 따로 밤아오도록 로직을 구현했습니다.
* * *
* * *
> [FE][FEATURE] 

- .env
- package-lock.json
- package.json
- src/App.js
- src/apis/UserAPICalls.js
- src/components/common/Header.js
- src/modules/UserModule.js
- src/pages/user/Login.js
- src/pages/user/Test.js
- src/utils/TokenUtils.js
* * *
- #37
* * *
* * *
- 로그인 기능 추가
- 로그아웃 기능 추가
* * *
- 로그인 관련된 module, api 추가
- 토큰으로 인한 jwt디코드 및 쿠키 저장하는 디펜던시 추가
```
npm install react-cookie
npm install jwt-decode
```
-로그인에 대한 header 및 App.js 수정
* * *
- 쿠키에서 토큰 내용 추출할 수 있는 예시 파일 추가했습니다.
- 오류 사항을 작성하세요.
* * *
- 쿠키 토큰 정보 디코딩 및 추출
- 로그인 테스트(성공)
- 로그아웃 테스트(성공)
* * *
- 구현 시 쿠키 내 토큰에 꼭 필요한 정보있으면 말씀해주세요.
> [FE][Feature] 로그인 기능 추가

- .idea/.gitignore
- .idea/FE-oiljang-1123-01.iml
- .idea/inspectionProfiles/Project_Default.xml
- .idea/misc.xml
- .idea/modules.xml
- .idea/vcs.xml
- src/apis/MessageAPICalls.js
- src/components/common/Footer.js
- src/pages/message/MessageDetail.js
- src/pages/message/MessageList.js
- src/styles/Footer.module.css
- src/styles/message/MessageList.module.css
* * *
- #34  
* * *
* * *
- 쪽지 등록(답장하기) 기능 완성했습니다.
* * *
- msgDetail에서 컴포넌트는 바뀌지 않고, textArea만 활성화된 채로 새 메시지로 insert되는 것이기 때문에 useEffect에서 값을 받아와서 기존 쪽지 회원정보 및 게시글 정보 + 새로 등록한 쪽지 내용 및 쪽지 코드 등록되게 했습니다.
```
```
* * *
* * *
- 임의로 작성한 쪽지답장이 리스트에 다시 조회되는 것을 볼 수 있습니다.
* * *
> [FE][FEATURE] 쪽지 등록 완성

- src/styles/message/MessageList.module.css
* * *
- #32  
* * *
* * *
- 쪽지 리스트 CSS 수정했습니다.
* * *
* * *
* * *
* * *
> [FE][BUG]쪽지 리스트 조회 관련

- src/pages/product/Main.js
- src/styles/MainLayout.module.css
- src/styles/SubHeader.module.css
* * *
- #75 
* * *
* * *
메인페이지 가운데 정렬 안 된 부분, nav 디자인
* * *
메인페이지, subheader의 style 부분을 변경했습니다.
* * *
* * *
* * *
> [FE][FEATURE] 메인 페이지, nav 디자인 어긋난 거 수정

- src/pages/product/ProductEdit.js
- src/styles/SubHeader.module.css
* * *
- #25
* * *
* * *
- 진행중입니다,,,
> [FE][FEATURE] 상품수정 진행중

- src/pages/product/ProductEdit.js
* * *
- #25 
* * *
* * *
- 상품수정 진행중입니다...
* * *
- Received productCode: undefined 라고 뜨네요...
- 
* * *
- 좀만 기다려주세요,,, 이번 주 까지 완성하겠습니다...
> [FE][FEATURE]상품 수정 진행중

- src/apis/ReportAPICalls.js
- src/pages/report/ProcessManagement.js
- src/pages/report/ReportSearch.js
- src/pages/report/Search.js
* * *
- #21 
* * *
* * *
- 신고 기능 페이징 처리 구현 했습니다
* * *
- 페이징처리를 위한 기본 셋팅
```
// paging setting 
const pageInfo = result && result.pageInfo;
const [start, setStart] = useState(0);
const [currentPage, setCurrentPage] = useState(1);
const [pageEnd, setPageEnd] = useState(1);
const pageNumber = [];
if (pageInfo && pageInfo) {
for (let i = 1; i <= pageInfo.pageEnd; i++) {
pageNumber.push(i);
}
}
useEffect(() => {
setStart((currentPage - 1) * 5);
dispatch(callReportManagementAPI({
currentPage: currentPage
}));
}, [currentPage]);
```
- 페이징 처리를 위한 버튼 생성 또는 번호 생성 하였습니다.
```
{Array.isArray(resutList) &&
<button
onClick={() => setCurrentPage(currentPage - 1)}
disabled={currentPage === 1}
className={Button.buttons}>&lt;</button>
}
{pageNumber.map((num) => (
<li key={num} onClick={() => …
```
> :monocle_face: [FE][REATURE]신고기능 페이징 구현

- src/apis/UserAPICalls.js
- src/pages/user/Join.js
- src/pages/user/Login.js
* * *
- #37
* * *
* * *
- 구글 로그인 기능 추가
- 회원 가입 내용 추가
- 회원 관련 필요한 컴포넌트들 추가
* * *
- 로그인 컴포넌트 내 구글 로그인 내용 추가
- 회원 가입 컴포넌트 내 로직 추가
- 회원 관련 필요한 컴포넌트 추가
* * *
- 구글 로그인은 테스터로 등록한 사람만 가능합니다.
* * *
- 구글 로그인 완료
* * *
- 테스트 시 구글 계정을 테스터로 등록해야합니다.
> [FE][Feature] 로그인 추가

- src/apis/ProductEditAPICalls.js
- src/pages/product/AddProduct.js
- src/pages/product/MyProductList.js
- src/pages/product/ProductEdit.js
- src/pages/product/UsedProductDetailInfo.js
* * *
- #25 
* * *
* * *
- 상품수정 완료했습니다.
* * *
``
const updatedFields = {
price: parseFloat(price) || 0, // price가 NaN이면 0으로 설정
productDesc: productDesc || '', // productDesc가 undefined이면 빈 문자열로 설정
productName: productName || '', // productName이 undefined이면 빈 문자열로 설정
refCategoryCode: refCategoryCode || '', // refCategoryCode가 undefined이면 빈 문자열로 설정
wishPlaceTrade: wishPlaceTrade || '',
};
console.log('Product Code:', params.productCode);
console.log('Updated Fields:', updatedFields);
try {
await callProductEditAPI(params.productCode, updatedFields);
console.log('Received productCode:', productCode);
console.log('Received updatedFields:', updatedFields);
console.log('상품 수정 완료');
alert('상품 수정이 완료되었습니다. 메인페이지로 이동합니다.')
navigate('/');
} catch (error) {
console.error('상품 수정 중 에러 발생:', error);
} …
> [FE][BUG]상품수정 완료

- src/apis/MessageAPICalls.js
- src/components/message/Message.js
- src/components/message/MessageMenu.js
- src/pages/message/MessagModal.js
- src/pages/message/MessageList.js
- src/pages/product/UsedProductDetailInfo.js
- src/styles/Modal.module.css
- src/styles/message/MessageList.module.css
* * *
- #34 
* * *
* * *
- 쪽지 모달 조회 완성
- 쪽지 모달 등록(쪽지 답장) 완성
* * *
- 쪽지 모달에서 보내는사람/받는사람 조회해오고
```
const productUserInfo = useSelector(state => state.productReducer.getProductDetail);
console.log("productUserInfo: ", productUserInfo)
const productCode = productUserInfo.productDetail[0].productCode;
console.log("productCode : " + productCode)
const senderCode = jwtDecode(getCookie("accessToken")).userCode;
console.log("senderCode : " + senderCode)
const receiverCode = productUserInfo.productDetail[0].refUserCode;
console.log("receiverCode : " + receiverCode)
const params = useParams();
const dispatch = useDispatch();
const navigate = useNavigate();
console.log("token :" + JSON.stringify(jwtDecode(getCookie("accessToken"))))
```
보내는사람은 현재 로그인한 유저로, 토큰에서 가져왔고, 받는 사람은 게시글 데이터의 refUserCode로 …
> [FE][FEATURE]쪽지 모달 완성

- src/apis/ProductEditAPICalls.js
- src/pages/product/AddProduct.js
- src/pages/product/MyProductList.js
- src/pages/product/ProductEdit.js
- src/styles/product/AddProduct.css
* * *
- #31 
* * *
* * *
- 판매목록 상태관리 진행중입니다...
* * *
- 완료하면 바로 올리겠습니다
* * *
-
> [FE][FEATURE]내판매목록 진행중

- package-lock.json
- src/App.js
- src/AuthCheck.js
- src/apis/MyCalendarAPICalls.js
- src/components/MyCalendar/MyCalenderMain.js
- src/components/common/SubHeader.js
- src/components/product/MergeBox.js
- src/modules/MyCalendarModule.js
- src/pages/product/Merge.js
- src/pages/product/UsedProductDetail.js
- src/pages/product/UsedProductDetailInfo.js
- src/styles/Button.module.css
- src/styles/Modal.module.css
- src/styles/myCalendar/MyCalendar.css
- src/styles/myCalendar/MyCalendarAside.css
* * *
- #95 
* * *
* * *
캘린더로 일정 관리 가능하도록 했습니다.
* * *
app.js, subHeader.js를 수정했습니다. 이제 메뉴에 일정 관리를 추가해서 서브 헤더 메뉴가 5가지입니다.
* * *
* * *
* * *
캘린더가 오류가 있을 수 있습니다. 실사용시에 잘 드러나지 않지만 거슬릴 수 있습니다.
> [FE][Feature] 캘린더로 일정 관리

- package-lock.json
- src/pages/product/AddProduct.js
- src/pages/product/ProductEdit.js
- src/styles/product/AddProduct.css
- src/styles/product/ProductEdit.css
* * *
- #22 
* * *
* * *
- state에 따른 버튼 스타일 변화
- 가격 입력시 문자열 입력 방지 및 숫자 입력시 , 단위로 찍힘
* * *
``
const handlePriceChange = (event) => {
if (priceOption === 'sell') {
const inputValue = event.target.value;
const numericValue = inputValue.replace(/[^0-9]/g, ''); // 숫자 이외의 문자 제거
if (numericValue > 1000000000) {
alert('10억 이상의 값은 입력할 수 없습니다.');
return;
}
setPrice(numericValue);
}
};
``
* * *
-
> [FE][Feature] 상품추가 state에 따른 버튼 스타일 변화

- src/App.js
- src/apis/InquiryAPICalls.js
- src/components/common/SubHeader.js
- src/pages/inquery/InquiryDetail.js
- src/pages/inquery/InquiryList.js
* * *
- #33 
* * *
* * *
- 1:1 문의 조회 기능입니다.
* * *
- 페이징 버튼 추가 및 category, status, keyword검색 조회 기능 진행중입니다.
- 조회 페이지는 관리자("ROLE_ADMIN") 과 유저("ROLE_USER")에 따라 화면 출력이 조금씩 다르게 출력됩니다
* * *
- 아직 미완성입니다!!
* * *
* * *
> [FE][FEATURE]1:1문의 항목별  조회

- src/pages/product/AddProduct.js
- src/pages/product/ProductEdit.js
- src/styles/product/AddProduct.css
- src/styles/product/ProductEdit.css
* * *
- #25 
* * *
* * *
- 상품수정 css 디자인
* * *
-`` <div className="pricebtn">
<label className='custom-radio' style={{ backgroundColor: priceOption === 'sell' ? '#222222' : '#C7C6C6' }}>
<input
type="radio"
name="price_option"
value="sell"
required
checked={priceOption === 'sell'} // 추가된 부분
onChange={() => handlePriceOptionChange('sell')}
/>
판매하기
</label>
<label className='custom-radio' style={{ backgroundColor: priceOption === 'share' ? '#222222' : '#C7C6C6' }}>
``
* * *
-
> [FE][FEATURE]상품수정 css디자인

- src/App.js
- src/apis/MyCalendarAPICalls.js
- src/components/MyCalendar/MyCalenderMain.js
- src/components/common/Header.js
- src/components/common/SubHeader.js
- src/modules/MyCalendarModule.js
- src/pages/MyCalendar/MyCalendar.js
- src/pages/product/UsedProductDetailInfo.js
- src/pages/user/Login.js
- src/styles/ImageGallery.css
- src/styles/MainLayout.module.css
- src/styles/myCalendar/MyCalendar.css
* * *
- #95 
* * *
* * *
캘린더 버그 수정했고, 시간 저장 가능합니다.
* * *
캘린더에 시간란 추가
* * *
.getDate 버그는 실사용시 문제가 없는 버그입니다.
* * *
* * *
> [FE][FEATURE] 캘린더 버그 수정 및 시간 추가

- src/pages/product/UsedProductDetailInfo.js
* * *
- #25
* * *
* * *
productEdit 링크 이동 작동 안 되는 버그 해결했습니다.
* * *
productEdit navigate공란 없앴습니다.
* * *
* * *
* * *
> [FE][BUG] productEdit navigate공란 없앴습니다.

- src/apis/SanctionsAPICalls.js
- src/modules/SanctionsModule.js
- src/pages/report/ProcessManagement.js
- src/pages/report/ReportUpdate.js
- src/pages/userSanctions/SanctionsManagement.js
* * *
- #
* * *
* * *
정책에 맞게 사용자를 로그인 제한 할 수 있도록 날짜 update하였습니다.
* * *
- 날짜 포맷 할때 주의 해야합니다.
```
const isoPermanentSuspension = permanentSuspension.toISOString();
```
- ISO 으로 포맷을해야 백엔드에서 받을 수 있습니다.
* * *
```
//현재 날짜
const currentDate = new Date();
const isoCurrentDate = currentDate.toISOString();
// 7일 이후의 날짜 
const afterSevenDays = new Date();
afterSevenDays.setDate(currentDate.getDate() + 7);
const isoAfterSevenDays = afterSevenDays.toISOString();
// 30일 이후의 날짜
const afterThirtyDays = new Date();
afterThirtyDays.setDate(currentDate.getDate() + 30);
const isoAfterThirtyDays = afterThirtyDays.toISOString();
// 영구 정지
const permanentSuspension = new Date();
permanentSuspension.setDate(currentDate.getFullYear() + 1000);
const isoPermanentSuspension = permanentSuspension.toISOString();
const …
```
> :fire: [BE][FEATURE]사용자제제 update완료

- src/apis/MessageAPICalls.js
- src/pages/message/MessageList.js
- src/styles/message/MessageList.module.css
* * *
- #32 
* * *
* * *
- 쪽지 키워드 조회 관련해서 수정중입니다
* * *
- form태그로 input type=submit으로 요청을 날렸는데 랜더링이 기본으로 되기 때문에 보낸 쪽지함 조회에 적합하지 않았습니다. 그래서 input type을 button으로 바꾼 후 onClick 핸들러로 api를 호출하는 것으로 수정중입니다.
* * *
- 아직 keyword 값을 받아오지 못해 undefined인 상태입니다
```
const onSearchHandler = () => {
dispatch(callMessageListAPI({
userCode: jwtDecode(getCookie("accessToken")).userCode,
isReceived: isReceived,
page: page,
keyword: keyword,
})).then((result) => {
console.log("keyword============"+ keyword)
console.log("page============"+ page)
console.table("result : " + result);
if(result && result.data){
setMessageList([result.data.results]);
if(!curURL.searchParams.get('page')){
dispatch({type: GET_PAGING, payload: 0});
}
console.log("keyword============"+ keyword)
}else{
console.error('[MessageList] API …
```
> [FE][BUG]쪽지 키워드 조회 수정

- src/apis/ReportAPICalls.js
- src/apis/SanctionsAPICalls.js
- src/components/common/Header.js
- src/pages/product/UsedProductDetailInfo.js
- src/pages/report/Report.js
- src/pages/report/ReportUpdate.js
- src/pages/userSanctions/SanctionsManagement.js
* * *
- #107 
* * *
* * *
- 사용자제재 로그인 제한 중복처리에 방지 처리 
* * *
- 기존에 같은 유저가 여러개등록이 되었을때 처리를 중복으로 할 수 있었으나 처리가완료되면 제제 기한을 제제된 날짜로 볼 수 있게 변경하였습니다.
* * *
```
{sanctions.map((sanction) => (
<tbody key={sanction.sanctionsCode}>
<tr>
<th>{sanction.nickName}({sanction.userId})</th>
<th>{sanction.count}</th>
<th>{sanction.sanctionsDate === null ? (
<select
onChange={onChangeHandler}
name="sanctionsDate">
<option disabled selected hidden="hidden">제재기한</option>
<option value={isoAfterSevenDays}>7일</option>
<option value={isoAfterThirtyDays}>30일</option>
<option value={isoPermanentSuspension}>영구정지</option>
</select>) : (<>{formatDateFromArray(sanction.sanctionsDate)}</>
)}
</th>
<th>
{sanction.sanctionsDate === null ? (
<button
onClick={() => { onClickSanctionsUpdateHandler(sanction.refUserCode, …
```
> :art: [BE][Feature] 사용자제재 중복 처리 방지

- src/components/product/MergeBox.js
- src/components/product/ProductCategory.js
- src/pages/product/Merge.js
- src/pages/product/UsedProductDetailInfo.js
* * *
- #45 
* * *
* * *
예산이 0원일 경우 처음에는 alert을 띄우도록 했습니다.
* * *
MergeBox.js에서 예산 기본값 0원, 없애고 엔터 누룰 경우 0원, 처음 입력시 0원일 경우 alert
* * *
* * *
* * *
> [FE][FEATURE] 예산 0원이고 처음 일 시 알람

- src/pages/product/AddProduct.js
* * *
- 
* * *
* * *
- 설명을 작성하세요.
- 설명을 작성하세요.
* * *
- 변경 사항을 작성하세요.
- 변경 사항을 작성하세요.
* * *
- 오류 사항을 작성하세요.
- 오류 사항을 작성하세요.
* * *
- 테스트 내용 및 결과를 작성하세요.
- 테스트 내용 및 결과를 작성하세요.
* * *
- 요청 사항을 작성하세요.
- 요청 사항을 작성하세요.
> 20231207-product-003 스토리지 저장해서 7일 동안 안 보기로 했습니다.

- src/apis/MessageAPICalls.js
- src/pages/inquery/InquiryAdmin.js
- src/pages/inquery/InquiryDetail.js
- src/pages/inquery/InquiryList.js
- src/pages/message/MessageDetail.js
- src/pages/message/MessageList.js
* * *
- 
* * *
* * *
-쪽지 조회 관련해서 수신일시를 표시할 때 -(하이픈)넣어주었고, -9시간으로 변형되어 나오는 거 수정했습니다
* * *
- 출력할 때 코드 바꿨습니다.
- insert할 때 api에서 보내는 요청에서 날짜에 +18해서 시간을 맞춰줬습니다
* * *
* * *
* * *
> [FE][BUG]쪽지 조회 수정

- src/pages/product/Merge.js
* * *
- #30 
* * *
* * *
꾸러미를 7일 동안 안 보기 가능하도록 했습니다.
* * *
Merge.js 변경
* * *
* * *
* * *
> [FE][FEATURE] 꾸러미 팝업 기간 제한
